name: Test suite for Loggo2
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v4
        with:
          python-version: '${{ matrix.python-version }}'
      - uses: actions/checkout@v3
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: |
          poetry install
      - name: Run lint checks
        run: |
          poetry run flake8 .
          poetry run mypy .
          poetry run black --check .
          poetry run docformatter --recursive --check loggo/ tests/ setup.py
          poetry run isort --check-only -rc .
      - name: Run test suite
        run: pytest --cov --cov-fail-under=95
